[project]
name = "pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
codespell = ">=2.2.6,<2.3"
cmake = ">=3.28.3,<3.29"
compilers = ">=1.7.0,<1.8"
cmake-format = ">=0.6.13,<0.7"
npx = ">=0.1.1,<0.2"
doxygen = ">=1.10.0,<1.11"
ninja = ">=1.11.1,<1.12"
ghostscript = ">=10.2.1,<10.3"
texlive-core = ">=20230313,<20230314"
pip = ">=24.0,<25"
cppcheck = ">=2.13.1,<2.14"
nvim = ">=0.9.5,<0.10"
prettier = ">=3.2.5,<3.3"
nodejs = ">=20.9.0,<20.10"
cuda = "*"
pkg-config = ">=0.29.2,<0.30"
fish = ">=3.7.0,<3.8"
vcpkg = ">=2023.4.15,<2023.5"
