[project]
name = "pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
codespell = ">=2.2.6,<2.3"
ninja = ">=1.11.1,<1.12"
cmake-format = ">=0.6.13,<0.7"
ghostscript = ">=10.3.0,<10.4"
fish = ">=3.7.1,<3.8"
cmake = ">=3.29.1,<3.30"
python = ">=3.12.2,<3.13"
cppcheck = ">=2.13.4,<2.14"
pip = ">=24.0,<25"
nodejs = ">=20.9.0,<20.10"
doxygen = ">=1.10.0,<1.11"
npx = ">=0.1.1,<0.2"
texlive-core = ">=20230313,<20230314"
catch2 = ">=3.5.3,<3.6"
compilers = ">=1.7.0,<1.8"
pkg-config = ">=0.29.2,<0.30"
prettier = ">=3.2.5,<3.3"
nvim = ">=0.9.5,<0.10"

