[project]
name = "pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.12.2,<3.13"
nvim = ">=0.9.5,<0.10"
cmake-format = ">=0.6.13,<0.7"
prettier = ">=3.2.5,<3.3"
fish = ">=3.7.1,<3.8"
pkg-config = ">=0.29.2,<0.30"
codespell = ">=2.2.6,<2.3"
pip = ">=24.0,<25"
ghostscript = ">=10.3.0,<10.4"
doxygen = ">=1.10.0,<1.11"
texlive-core = ">=20230313,<20230314"
cppcheck = ">=2.13.2,<2.14"
compilers = ">=1.7.0,<1.8"
cmake = ">=3.28.3,<3.29"
ninja = ">=1.11.1,<1.12"
nodejs = ">=20.9.0,<20.10"
npx = ">=0.1.1,<0.2"
cuda = ">=12.4.0,<12.5"

